Repository beefyfinance/beefy-v2, pull requests merged in 2022-11, with the labels that each got.

#1142 Add Ferro
  src/config/platforms.json
  src/config/vault/cronos.json
Labels: vault-pr

#1152 [Update] Header Logo
  src/components/Header/Header.tsx
  src/images/bifi-logos/header-logo-eyes.png
  src/images/bifi-logos/header-logo-notext-eyes.png
Labels: ux-ok

#1158 Add Stargate Eth
  src/config/config.tsx
  src/config/vault/ethereum.json
  src/helpers/utils.tsx
  src/images/single-assets/sethETH.svg
  src/images/single-assets/sethUSDC.svg
  src/images/single-assets/sethUSDT.svg
Labels: vault-pr

#1144 add boo-usdc-dei
  src/config/vault/fantom.json
Labels: vault-pr

#1155 Add MAI 4pool
  src/config/vault/moonbeam.json
  src/images/single-assets/stella4pool.png
Labels: vault-pr

#1172 Add trust wallet extension + EOL empty vault
  src/config/vault/bsc.json
  src/features/data/apis/wallet/custom-injected-wallets.ts
Labels: ux-ok, vault-pr

#1160 Add Hop OP
  src/config/platforms.json
  src/config/vault/optimism.json
Labels: vault-pr

#1175 Fix mint text
  src/features/vault/components/MinterCards/MintBurnCard/components/Mint.tsx
Labels: ux-ok

#1176 [UPDATE] partners
  src/features/data/apis/config-types.ts
  src/features/data/apis/config.ts
  src/features/data/reducers/filtered-vaults.ts
  src/features/data/reducers/partners.ts
  src/features/data/selectors/filtered-vaults.ts
  src/features/data/selectors/partners.ts
  src/features/home/components/Filters/components/ExtendedFilters/ExtendedFilters.tsx
  src/features/vault/components/GamesCards/GamesCards.tsx
  src/features/vault/components/GamesCards/index.tsx
  src/features/vault/components/GamesCards/styles.tsx
  src/features/vault/components/MoonportCard/index.tsx
  src/features/vault/vault.tsx
  src/helpers/partners.tsx
  src/images/partners/moonpot.svg
  src/locales/en/main.json
  src/locales/zh/main.json
Labels: ux-ok

#1178 [UPDATE] add pool address link
  src/features/vault/components/GovDetailsCard/GovDetailsCard.tsx
  src/features/vault/components/GovDetailsCard/styles.tsx
  src/locales/en/main.json
Labels: ux-ok

#1179 [FIX] stables exposure
  src/features/dashboard/components/StablesExposure/StablesExposure.tsx
  src/features/data/selectors/balance.ts
Labels: ux-ok

#1180 [UPDATE] dashboard banner
  src/components/AnnouncementBanner/AnnouncementBanner.tsx
  src/components/AnnouncementBanner/index.tsx
  src/components/AnnouncementBanner/styles.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/MobileMenu/MobileMenu.tsx
  src/components/Header/components/NavItem/NavItem.tsx
  src/components/Header/list.tsx
  src/components/ProposalBanner/ProposalBanner.tsx
  src/components/ProposalBanner/index.tsx
  src/features/home/home.tsx
  src/images/icons/dashboard.svg
Labels: ux-ok

#1182 Add ren notice + pause ren vaults + add glp deposit notice + bip58 banner
  src/components/AnnouncementBanner/AnnouncementBanner.tsx
  src/components/Banners/AnnouncementBanner/AnnouncementBanner.tsx
  src/components/Banners/AnnouncementBanner/index.tsx
  src/components/Banners/AnnouncementBanner/styles.tsx
  src/components/Banners/Banner/Banner.tsx
  src/components/Banners/Banner/index.tsx
  src/components/Banners/Banner/styles.tsx
  src/components/Banners/RenBanner/RenBanner.tsx
  src/components/Banners/RenBanner/index.tsx
  src/components/Banners/RenBanner/styles.tsx
  src/config/vault/arbitrum.json
  src/config/vault/avax.json
  src/config/vault/fantom.json
  src/config/vault/featured.json
  src/config/vault/polygon.json
  src/features/data/entities/vault.ts
  src/features/data/selectors/balance.ts
  src/features/home/home.tsx
  src/features/home/styles.tsx
  src/features/vault/components/Deposit/Deposit.tsx
  src/features/vault/components/GlpNotices/GlpDepositNoticeImpl.tsx
  src/features/vault/components/GlpNotices/GlpNotice.tsx
  src/features/vault/components/GlpNotices/GlpWithdrawNoticeImpl.tsx
  src/features/vault/components/GlpNotices/index.tsx
  src/features/vault/components/GlpNotices/styles.ts
  src/features/vault/components/GlpWithdrawCountdown/GlpWithdrawCountdown.tsx
  src/features/vault/components/GlpWithdrawCountdown/index.tsx
  src/features/vault/components/Withdraw/Withdraw.tsx
  src/features/vault/vault.tsx
  src/helpers/useLocalStorageBoolean.tsx
  src/locales/en/main.json
Labels: ux-ok

#1173 [UPDATE] Upcoming Boost box
  src/components/VaultStats/VaultDailyStat.tsx
  src/components/VaultStats/VaultYearlyStat.tsx
  src/config/platforms.json
  src/features/data/selectors/boosts.ts
  src/features/home/components/Vault/components/VaultValueStat/VaultValueStat.tsx
  src/features/vault/components/BoostWidget/BoostWidget.tsx
  src/features/vault/components/BoostWidget/BoostWidgetActiveBoost.tsx
  src/locales/en/main.json
Labels: ux-ok

#1183 Add Moo Beamswap wstDOT-xcDOT
  src/config/vault/moonbeam.json
Labels: vault-pr
