Repository beefyfinance/beefy-v2, pull requests merged in 2022-06, with the labels that each got.

#823 Enable TUSD withdraws + show TUSD/FRAX liquidity
  src/components/Alerts/styles.ts
  src/features/vault/components/ScreamAvailableLiquidity/ScreamAvailableLiquidity.tsx
  src/features/vault/components/ScreamAvailableLiquidity/hooks.ts
  src/features/vault/components/ScreamAvailableLiquidity/index.tsx
  src/features/vault/components/ScreamAvailableLiquidity/styles.ts
  src/features/vault/components/Withdraw/Withdraw.tsx
Labels: ux-ok

#824 Platform: Beefy.Finance -> Beefy
  src/config/boost/fantom.json
  src/config/vault/arbitrum.json
  src/config/vault/aurora.json
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/celo.json
  src/config/vault/cronos.json
  src/config/vault/fantom.json
  src/config/vault/fuse.json
  src/config/vault/harmony.json
  src/config/vault/heco.json
  src/config/vault/metis.json
  src/config/vault/moonbeam.json
  src/config/vault/moonriver.json
  src/config/vault/polygon.json
  src/features/data/reducers/platforms.ts
Labels: ux-ok

#828 Quicker validation script
  scripts/validatePools.js
Labels: vault-pr

#821 Retire vaults due to underlying rewards stopped
  src/config/vault/avax.json
  src/config/vault/cronos.json
  src/config/vault/fantom.json
  src/config/vault/harmony.json
Labels: vault-pr

#825 add support to address with ens
  package-lock.json
  package.json
  src/components/Header/components/WalletContainer/WalletContainer.tsx
  src/features/data/actions/wallet.ts
  src/features/data/reducers/wallet/wallet.ts
  src/features/data/selectors/wallet.ts
  src/helpers/format.tsx
  yarn.lock
Labels: ux-ok, code-ok

#838 [UPDATE] add/remove theme imports
  src/components/LinkButton/styles.tsx
  src/components/Loader/styles.tsx
  src/components/NetworkStatus/NetworkStatus.tsx
  src/components/NetworkStatus/styles.ts
  src/components/Popover/styles.tsx
  src/features/home/components/Filters/components/UserCategoryFilters/styles.ts
  src/features/vault/components/Card/CardActions/styles.tsx
  src/features/vault/components/Graph/styles.tsx
  src/features/vault/components/TokenWithDeposit/styles.ts
  src/features/vault/components/VaultBuyLinks/styles.ts
  src/features/vault/components/VaultsStats/styles.tsx
Labels: code-ok

#839 EOL multiple quickswap vaults
  src/config/vault/polygon.json
Labels: vault-pr

#817 add new moonbeam pools
  src/config/vault/moonbeam.json
  src/images/single-assets/DAIs.png
  src/images/single-assets/USDTs.svg
Labels: vault-pr

#822 add new babyswap pools
  src/config/vault/bsc.json
Labels: vault-pr

#844 Surface retired and paused vaults on My Vaults
  src/features/data/selectors/filtered-vaults.ts
Labels: ux-ok

#842 Show Avg. APY on screens >= 430px width
  src/features/home/components/Portfolio/UserStats/UserStats.tsx
Labels: ux-ok

#847 remove button inside <a> tag and update buy links
  src/features/vault/components/InsuranceCard/InsuranceCard.tsx
  src/features/vault/components/InsuranceCard/styles.tsx
  src/features/vault/components/MoonportCard/MoonpotCard.tsx
  src/features/vault/components/MoonportCard/styles.tsx
  src/features/vault/components/VaultBuyLinks/VaultBuyLinks.tsx
Labels: ux-ok

#850 upgrade zap options font
  src/features/vault/components/Deposit/Deposit.tsx
  src/features/vault/components/TokenWithBalance/TokenWithBalance.tsx
  src/features/vault/components/TokenWithBalance/styles.ts
  src/features/vault/components/TokenWithDeposit/TokenWithDeposit.tsx
  src/features/vault/components/TokenWithDeposit/styles.ts
  src/features/vault/components/Withdraw/Withdraw.tsx
Labels: design-ok, ux-ok

#849 EOL 27 vaults
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/cronos.json
  src/config/vault/fantom.json
  src/config/vault/metis.json
  src/config/vault/moonbeam.json
Labels: vault-pr

#852 Hotfix vault lists
  src/config/vault/avax.json
  src/config/vault/cronos.json
  src/config/vault/featured.json
  src/config/vault/polygon.json
  src/features/data/selectors/tokens.ts
Labels: ux-ok

#854 Fix boost sorting
  src/features/data/selectors/filtered-vaults.ts
Labels: ux-ok

#858 Add Biswap farms
  src/config/vault/bsc.json
Labels: vault-pr

#851 Platforms rework
  package.json
  scripts/config.js
  scripts/config.ts
  scripts/getPoolCreationTimestamp.ts
  scripts/launchpool.ts
  scripts/migratePlatform.ts
  scripts/utils.mjs
  scripts/utils.ts
  scripts/validatePools.ts
  src/components/VaultPlatform/VaultPlatform.tsx
  src/components/VaultPlatform/index.tsx
  src/config/abi/boost.json
  src/config/platforms.json
  src/config/strategy-types.json
  src/config/vault/arbitrum.json
  src/config/vault/aurora.json
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/celo.json
  src/config/vault/cronos.json
  src/config/vault/emerald.json
  src/config/vault/fantom.json
  src/config/vault/fuse.json
  src/config/vault/harmony.json
  src/config/vault/heco.json
  src/config/vault/metis.json
  src/config/vault/moonbeam.json
  src/config/vault/moonriver.json
  src/config/vault/polygon.json
  src/features/data/actions/platforms.ts
  src/features/data/actions/scenarios.ts
  src/features/data/actions/strategy-types.ts
  src/features/data/apis/config-types.ts
  src/features/data/apis/config.ts
  src/features/data/apis/instances.ts
  src/features/data/entities/platform.ts
  src/features/data/entities/strategy-type.ts
  src/features/data/entities/token.ts
  src/features/data/entities/vault.ts
  src/features/data/reducers/data-loader.ts
  src/features/data/reducers/platforms.ts
  src/features/data/reducers/strategy-types.ts
  src/features/data/reducers/tokens.ts
  src/features/data/reducers/vaults.ts
  src/features/data/selectors/data-loader.ts
  src/features/data/selectors/filtered-vaults.ts
  src/features/data/selectors/platforms.ts
  src/features/data/utils/config-hacks.ts
  src/features/home/components/Filters/components/PlatformFilters/PlatformDropdownFilter.tsx
  src/features/home/components/Vault/components/VaultTags/VaultTags.tsx
  src/features/vault/components/StrategyCard/StrategyCard.tsx
  src/features/vault/components/StrategyCard/StrategyDescription.tsx
  src/features/vault/components/StrategyCard/stratText.tsx
  src/features/vault/components/VaultMeta/index.tsx
  src/features/vault/vault.tsx
  src/locales/de/risksNstrats.json
  src/locales/en/main.json
  src/locales/en/risksNstrats.json
  src/locales/zh/risksNstrats.json
Labels: code-ok, vault-pr

#860 User category filter: fit at 360px width
  src/features/home/components/Filters/components/UserCategoryFilters/styles.ts
Labels: ux-ok

#861 [FIX] Show correct amount for bridge advice
  src/components/Bridge/components/Fees/Fees.tsx
  src/locales/en/main.json
Labels: ux-ok

#867 update transak config
  src/components/Transak/Transak.tsx
Labels: ux-ok

#846 Add Aave v3 LINK.e
  src/config/vault/avax.json
Labels: vault-pr

#864 add mai4pool on moonbeam
  src/config/vault/moonbeam.json
Labels: vault-pr

#869 EOL vaults due to underlying rewards ended + EOL Tombswap until they make security updates to new farms
  src/config/vault/avax.json
  src/config/vault/fantom.json
  src/config/vault/polygon.json
Labels: vault-pr

#872 Add config validation for strategyTypeId
  scripts/validatePools.ts
  src/config/vault/avax.json
Labels: vault-pr

#875 add beets vault
  src/config/vault/fantom.json
Labels: vault-pr

#865 LP breakdown
  src/components/AssetsImage/AssetsImage.tsx
  src/components/Header/Header.tsx
  src/components/ToggleButtons/styles.ts
  src/components/Tooltip/BasicTooltipContent.tsx
  src/components/Tooltip/styles.ts
  src/features/data/actions/apy.ts
  src/features/data/actions/prices.ts
  src/features/data/actions/scenarios.ts
  src/features/data/actions/tokens.ts
  src/features/data/apis/beefy.ts
  src/features/data/entities/token.ts
  src/features/data/reducers/data-loader.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/tokens.ts
  src/features/data/utils/feature-flags.ts
  src/features/home/components/Portfolio/UserStats/UserStats.tsx
  src/features/vault/components/Card/CardContent/CardContent.tsx
  src/features/vault/components/Card/CardHeader/CardHeader.tsx
  src/features/vault/components/Card/CardHeader/styles.tsx
  src/features/vault/components/Graph/CustomTooltip/CustomTooltip.tsx
  src/features/vault/components/Graph/Graph.tsx
  src/features/vault/components/InsuranceCard/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/LiquidityPoolBreakdown.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/BreakdownTable/BreakdownTable.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/BreakdownTable/index.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/BreakdownTable/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Chart/Chart.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Chart/index.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Chart/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/ChartWithLegend/ChartWithLegend.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/ChartWithLegend/index.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/ChartWithLegend/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Legend/Legend.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Legend/index.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Legend/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/hooks.tsx
  src/features/vault/components/LiquidityPoolBreakdown/index.tsx
  src/features/vault/components/LiquidityPoolBreakdown/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/types.ts
  src/features/vault/components/MinterCards/MintBurnCard/MintBurn.tsx
  src/features/vault/components/MoonportCard/styles.tsx
  src/features/vault/components/QiDaoCard/styles.tsx
  src/features/vault/components/TokenWithDeposit/TokenWithDeposit.tsx
  src/features/vault/vault.tsx
  src/helpers/addresses.ts
  src/helpers/big-number.ts
  src/helpers/format.tsx
  src/locales/en/main.json
Labels: ux-ok

#879 Update addLiquidityUrl and buyTokenUrl for hector-tor-crv vault
  src/config/vault/fantom.json
Labels: ux-ok

#886 Add pause reasons
  scripts/validatePools.ts
  src/components/ApyStats/ApyStats.tsx
  src/config/vault/arbitrum.json
  src/config/vault/aurora.json
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/celo.json
  src/config/vault/cronos.json
  src/config/vault/emerald.json
  src/config/vault/fantom.json
  src/config/vault/fuse.json
  src/config/vault/harmony.json
  src/config/vault/metis.json
  src/config/vault/moonbeam.json
  src/config/vault/moonriver.json
  src/config/vault/polygon.json
  src/features/data/apis/config-types.ts
  src/features/data/entities/vault.ts
  src/features/data/reducers/filtered-vaults.ts
  src/features/data/selectors/data-loader.ts
  src/features/data/selectors/filtered-vaults.ts
  src/features/home/components/Filters/components/ExtendedFilters/ExtendedFilters.tsx
  src/features/home/components/Vault/components/VaultStats/VaultDailyStat.tsx
  src/features/home/components/Vault/components/VaultStats/VaultYearlyStat.tsx
  src/features/vault/components/Graph/Graph.tsx
  src/features/vault/components/StrategyCard/StrategyCard.tsx
  src/locales/en/main.json
Labels: ux-ok, vault-pr

#882 adding vault vvs-ape-cro
  src/config/vault/cronos.json
Labels: vault-pr

#878 add optimism bg for vault network
  src/features/home/components/Vault/components/VaultIdentity/styles.ts
Labels: ux-ok

#887 EOL Avax Lending Vaults, Unpause DEUS-DEI
  src/config/vault/avax.json
  src/config/vault/fantom.json
Labels: vault-pr
