Repository beefyfinance/beefy-v2, pull requests merged in 2023-10, with the labels that each got.

#1763 Add OVN-USD+ Boost
  src/config/boost/optimism.json
Labels: boost-pr

#1758 Fix: addresses overflow on mobile
  src/features/dashboard/components/NoResults/NoResults.tsx
  src/features/dashboard/components/NoResults/styles.tsx
Labels: ux-ok

#1765 Fix: match filter and dropdowns paddings
  src/components/LabeledMultiSelect/styles.ts
  src/components/LabeledSearchMultiSelect/styles.ts
  src/components/LabelledCheckbox/styles.ts
  src/features/home/components/Filters/components/ChainFilters/styles.ts
  src/features/home/components/Filters/components/CheckboxFilter/styles.ts
Labels: ux-ok

#1768 Add Fireblocks wallet connector
  package.json
  src/features/data/apis/wallet/wallet-connection.ts
  src/images/wallets/fireblocks-transparent.svg
  src/images/wallets/fireblocks.svg
  yarn.lock
Labels: ux-ok

#1769 Fixs dashboard
  src/features/dashboard/components/UserVaults/components/MobileCollapseContent/components/VaultDashboardMobileStats/styles.tsx
  src/features/dashboard/components/UserVaults/components/Vault/Vault.tsx
  src/features/dashboard/hooks.tsx
  src/features/data/actions/wallet.ts
  src/features/data/selectors/analytics.ts
Labels: ux-ok

#1770 add snapshot balance
  src/components/Banners/SnapshotBalanceBanner/SnapshotBalanceBanner.tsx
  src/components/Banners/SnapshotBalanceBanner/index.tsx
  src/features/data/actions/snapshot-balance.ts
  src/features/data/apis/instances.ts
  src/features/data/apis/snapshot-balance/snapshot-balance-types.ts
  src/features/data/apis/snapshot-balance/snapshot-balance.ts
  src/features/data/reducers/wallet/balance.ts
  src/features/home/components/Banners/index.tsx
Labels: ux-ok

#1774 change snap date text
  src/components/Banners/SnapshotBalanceBanner/SnapshotBalanceBanner.tsx
Labels: ux-ok

#1778 fix: treasury token exposure
  src/features/data/selectors/treasury.ts
Labels: ux-ok

#1781 Update: Eol earning pools
  src/config/vault/arbitrum.json
  src/config/vault/aurora.json
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/canto.json
  src/config/vault/celo.json
  src/config/vault/cronos.json
  src/config/vault/ethereum.json
  src/config/vault/fantom.json
  src/config/vault/fuse.json
  src/config/vault/harmony.json
  src/config/vault/heco.json
  src/config/vault/kava.json
  src/config/vault/metis.json
  src/config/vault/moonbeam.json
  src/config/vault/moonriver.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
  src/features/vault/components/RetirePauseReason/RetirePauseReason.tsx
  src/locales/en/main.json
Labels: ux-ok

#1786 Re-enable 1inch zap
  src/features/data/actions/vaults.ts
Labels: ux-ok

#1793 Update banner
  src/components/Banners/SnapshotBalanceBanner/SnapshotBalanceBanner.tsx
Labels: ux-ok

#1792 Fix : Style bugs
  src/components/Header/Header.tsx
  src/components/Header/components/DropNavItem/types.ts
  src/components/Header/components/MobileMenu/MobileMenu.tsx
  src/components/Header/components/NavItem/NavItem.tsx
  src/components/Header/list.tsx
  src/features/home/components/Vault/styles.ts
Labels: ux-ok

#1795 Add Velodrome mooBIFI-ETH vLP
  src/config/vault/optimism.json
Labels: vault-pr

#1771 Change to managed-conc-lp strategyTypeId
  src/config/vault/arbitrum.json
  src/config/vault/bsc.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
  src/config/vault/zkevm.json
Labels: ux-ok

#1772 Fix :remove round move on deposit/withdraw inputs
  src/features/data/actions/wallet-actions.tsx
  src/features/data/apis/gas-prices/gas-prices.ts
  src/features/data/reducers/wallet/boost.ts
  src/features/vault/components/Actions/Transact/AmountInput/AmountInput.tsx
  src/features/vault/components/Actions/Transact/DepositTokenAmountInput/DepositTokenAmountInput.tsx
  src/features/vault/components/Actions/Transact/WithdrawTokenAmountInput/WithdrawTokenAmountInput.tsx
Labels: ux-ok

#1779 update :Add symbol treasury assets
  src/features/data/apis/config-types.ts
  src/features/data/selectors/treasury.ts
  src/features/treasury/components/DaoHoldings/components/AssetInfo/AssetInfo.tsx
  src/images/single-assets/RETRO.svg
Labels: ux-ok

#1797 Update favicon + remove some unused images
  public/favicon.ico
  src/components/Header/components/BifiPrice/BifiPrice.tsx
  src/images/bifi-logos/BIFI-COW.svg
  src/images/bifi-logos/BIFI-TOKEN.svg
  src/images/bifi-logos/bifi-zap-v2.svg
  src/images/bifi-logos/header-logo-eyes.png
  src/images/bifi-logos/header-logo-notext-eyes.png
  src/images/bifi-logos/logo-wizard-hover.png
  src/images/bifi-logos/logo-wizard-notext.png
  src/images/bifi-logos/logo-wizard.png
  src/images/bifi-logos/xmas-logo-notext.png
  src/images/bifi-logos/xmas-logo.png
Labels: ux-ok

#1798 Remove buyback
  src/features/data/actions/prices.ts
  src/features/data/actions/scenarios.ts
  src/features/data/apis/beefy/beefy-api.ts
  src/features/data/reducers/buyback.ts
  src/features/data/reducers/index.tsx
  src/features/data/selectors/buyback.ts
  src/features/data/utils/feature-flags.ts
  src/features/home/components/Portfolio/VaultsStats/VaultsStats.tsx
  src/locales/en/main.json
  src/locales/zh/main.json
  src/redux-types.ts
Labels: ux-ok

#1799 Update: beefy held stat on treasury
  src/features/data/selectors/treasury.ts
Labels: ux-ok

#1801 Fix OP mooBIFI id/oracleId when vaults load before addressbook
  src/features/data/reducers/tokens.ts
Labels: ux-ok
