Repository beefyfinance/beefy-v2, pull requests merged in 2023-12, with the labels that each got.

#1886 Add zapv3 campaign boosts
  src/config/boost/optimism.json
  src/config/boost/partners.json
Labels: boost-pr

#1885 Fix 1inch fee
  src/config/zap/zaps.json
  src/features/data/apis/transact/swap/one-inch/OneInchSwapProvider.ts
Labels: ux-ok

#1869 add partnerts link
  src/components/Footer/Footer.tsx
  src/components/Header/list.tsx
  src/images/icons/navigation/partners.svg
  src/locales/en/main.json
Labels: ux-ok

#1891 Add Sonne Base & OP
  src/config/platforms.json
  src/config/vault/base.json
  src/config/vault/optimism.json
Labels: vault-pr

#1888 Feat: boost campaigns
  src/components/LinkIcon/LinkIcon.tsx
  src/components/LinkIcon/styles.tsx
  src/components/VaultIdentity/components/VaultTags/VaultTags.tsx
  src/components/VaultIdentity/components/VaultTags/styles.ts
  src/config/boost/avax.json
  src/config/boost/bsc.json
  src/config/boost/campaigns.json
  src/config/boost/fantom.json
  src/config/boost/optimism.json
  src/config/boost/partners.json
  src/config/boost/polygon.json
  src/features/data/actions/boosts.ts
  src/features/data/apis/config-types.ts
  src/features/data/apis/config.ts
  src/features/data/entities/boost.ts
  src/features/data/entities/partner.ts
  src/features/data/reducers/boosts.ts
  src/features/data/reducers/partners.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/boosts.ts
  src/features/data/selectors/partners.ts
  src/features/vault/components/AddTokenToWallet/RewardTokenDetails.tsx
  src/features/vault/components/BoostCard/BoostCard.tsx
  src/features/vault/components/BoostCard/styles.tsx
  src/features/vault/components/ShareButton/ShareButton.tsx
  src/helpers/boostIconSrc.ts
  src/images/boosts/zap.svg
  src/locales/en/main.json
Labels: ux-ok

#1889 Feat: Add binance wallet provider
  package.json
  src/features/data/apis/wallet/custom-injected-wallets.ts
  src/features/data/apis/wallet/wallet-connection.ts
  src/images/wallets/binance-wallet.png
  src/images/wallets/binance-wallet.svg
  src/images/wallets/math-wallet.svg
  src/images/wallets/safepal-wallet.svg
  yarn.lock
Labels: ux-ok

#1895 Update: Boost styles
  src/features/data/actions/tokens.ts
  src/features/vault/components/Actions/Boosts/BoostActionButton/BoostActionButton.tsx
  src/features/vault/components/Actions/Boosts/BoostActionButton/styles.tsx
  src/features/vault/components/Actions/Boosts/styles.tsx
Labels: ux-ok

#1894 Feat: Add BUSD sunset banner
  src/components/Banners/BusdBanner/BusdBanner.tsx
  src/components/Banners/BusdBanner/index.tsx
  src/components/Banners/BusdBanner/styles.tsx
  src/components/Banners/RenBanner/index.tsx
  src/features/home/components/Banners/index.tsx
  src/features/vault/vault.tsx
Labels: ux-ok

#1893 Fix: Hide BIFI on onramp tokens list
  src/features/on-ramp/components/OnRamp/components/TokenStep/TokenStep.tsx
Labels: ux-ok

#1896 EOL 7 vaults Rewards, 3 vaults Platform TVL
  src/config/vault/arbitrum.json
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/ethereum.json
  src/config/vault/optimism.json
Labels: vault-pr

#1898 add next-usdc
  src/config/bridges.json
  src/config/vault/optimism.json
  src/images/bridges/connext.svg
  src/images/single-assets/NEXT.png
Labels: vault-pr

#1901 add xmas logos
  src/components/Header/Header.tsx
  src/images/bifi-logos/header-logo-notext-xmas.svg
  src/images/bifi-logos/header-logo-xmas.svg
Labels: ux-ok

#1903 fix: use date/shareDiff for old txs without a tx hash
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/Transaction.tsx
  src/features/data/actions/analytics.ts
  src/features/data/entities/analytics.ts
  src/features/data/reducers/analytics.ts
Labels: ux-ok

#1904 Update stargate links
  src/config/vault/avax.json
  src/config/vault/ethereum.json
Labels: ux-ok

#1905 Update: Loaders across app
  src/components/Loader/Loader.tsx
  src/components/Loader/index.ts
  src/components/Loader/styles.tsx
  src/components/LoadingIndicator/LoadingIndicator.tsx
  src/components/LoadingIndicator/styles.tsx
  src/features/home/components/Vaults/components/NoResults/NoResults.tsx
  src/features/vault/components/Actions/Minter/MinterCard.tsx
  src/images/loader.gif
  src/images/loader2.gif
Labels: ux-ok

#1913 EOL 3 vaults rewards, 3 vaults platform TVL
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/fuse.json
  src/config/vault/optimism.json
Labels: vault-pr

#1892 Feat/ Show Red dot when new article is published
  src/components/Header/Header.tsx
  src/components/Header/components/Badges/UnreadDots.tsx
  src/components/Header/components/Badges/UnreadProposalsCount.tsx
  src/components/Header/components/Badges/UnreadProposalsDot.tsx
  src/components/Header/components/Badges/hooks.tsx
  src/components/Header/components/MobileMenu/MobileMenu.tsx
  src/components/Header/components/NavItem/ArticlesMobileNavItem.tsx
  src/components/Header/components/NavItem/ArticlesNavItem.tsx
  src/components/Header/list.tsx
  src/features/data/actions/articles.ts
  src/features/data/apis/beefy/beefy-api.ts
  src/features/data/reducers/articles.ts
  src/features/data/reducers/data-loader-types.ts
  src/features/data/reducers/data-loader.ts
  src/features/data/reducers/index.tsx
  src/features/data/selectors/articles.ts
  src/features/data/selectors/data-loader.ts
  src/features/data/utils/feature-flags.ts
  src/redux-types.ts
Labels: ux-ok

#1922 Add 3 Sonne boosts
  src/config/boost/optimism.json
  src/images/single-assets/mooSonneOP.svg
Labels: boost-pr
