Repository beefyfinance/beefy-v2, pull requests merged in 2023-11, with the labels that each got.

#1815 Add mooBIFI boost
  src/config/boost/optimism.json
Labels: boost-pr

#1817 update Beefy info
  src/config/boost/partners.json
Labels: boost-pr

#1810 Update: Treasury update
  src/features/data/selectors/treasury.ts
  src/features/treasury/components/DaoHoldings/components/AssetInfo/AssetInfo.tsx
Labels: ux-ok

#1818 Add native USDC to OP zap
  src/config/zap/one-inch.json
Labels: ux-ok

#1808 Update price display etc
  src/App.tsx
  src/components/AddTokenToWallet/AddTokenToWallet.tsx
  src/components/AddTokenToWallet/index.tsx
  src/components/AddTokenToWallet/styles.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/BifiPrice/BifiPrice.tsx
  src/components/Header/components/BifiPrice/index.tsx
  src/components/Header/components/BifiPrice/styles.tsx
  src/components/Header/components/MobileMenu/MobileMenu.tsx
  src/components/Header/components/Prices/Prices.tsx
  src/components/Header/components/Prices/index.tsx
  src/components/Header/components/Prices/styles.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/styles.ts
  src/components/VaultLabelledStat/VaultLabelledStat.tsx
  src/features/dashboard/components/ShortAddress/ShortAddress.tsx
  src/features/data/actions/add-to-wallet.ts
  src/features/data/reducers/add-to-wallet.ts
  src/features/data/reducers/index.tsx
  src/features/data/selectors/add-to-wallet.ts
  src/features/vault/components/AddTokenToWallet/RewardTokenDetails.tsx
  src/features/vault/components/AddTokenToWallet/index.tsx
  src/features/vault/components/BoostCard/BoostCard.tsx
  src/images/icons/llama-swap.png
  src/images/icons/one-inch.svg
  src/locales/en/main.json
  src/redux-types.ts
  src/theme.ts
Labels: ux-ok

#1819 Treasury staked assets rework
  package.json
  src/config/config.tsx
  src/features/data/apis/config-types.ts
  src/features/data/selectors/treasury.ts
  src/features/treasury/components/DaoHoldings/components/Assets/hooks.tsx
  src/images/single-assets/aArbUSDCn.svg
  src/images/single-assets/aavUSDT.svg
  yarn.lock
Labels: ux-ok

#1825 Disable asset inline
  vite.config.ts
Labels: ux-ok

#1832 update links usdc > usdc.e
  src/config/vault/polygon.json
Labels: ux-ok

#1833 Fix intermittent dashboard crash
  src/features/data/actions/wallet.ts
  src/features/data/selectors/analytics.ts
Labels: ux-ok

#1829 Fix: Treasury
  src/features/data/selectors/treasury.ts
Labels: ux-ok

#1822 Bridged mooBIFI PNL
  src/components/Header/components/WalletContainer/WalletContainer.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/Transaction.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/styles.tsx
  src/features/data/actions/analytics.ts
  src/features/data/actions/scenarios.ts
  src/features/data/apis/analytics/analytics-types.ts
  src/features/data/entities/analytics.ts
  src/features/data/middlewares/wallet.ts
  src/features/data/reducers/analytics.ts
  src/features/data/reducers/vaults.ts
  src/features/data/selectors/analytics.ts
  src/features/data/selectors/balance.ts
  src/features/data/selectors/vaults.ts
  src/features/vault/components/PnLGraph/hooks.tsx
Labels: ux-ok

#1835 Enable CCIP bridge
  src/config/beefy-bridge.ts
Labels: ux-ok

#1838 Update base zap fee recipient
  src/config/zap/one-inch.json
Labels: ux-ok

#1841 UI Updates
  src/components/Banners/SnapshotBalanceBanner/SnapshotBalanceBanner.tsx
  src/components/Banners/SnapshotBalanceBanner/index.tsx
  src/components/VaultStats/VaultPnlStat.tsx
  src/config/bridges.json
  src/config/config.tsx
  src/config/vault/featured.json
  src/features/data/selectors/tokens.ts
  src/features/home/components/Banners/index.tsx
  src/images/bridges/ibc.svg
Labels: ux-ok

#1840 Eol vaults20231110
  src/config/vault/arbitrum.json
  src/config/vault/avax.json
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/cronos.json
  src/config/vault/ethereum.json
  src/config/vault/moonbeam.json
  src/config/vault/optimism.json
  src/config/vault/zksync.json
Labels: vault-pr

#1843 fix: recalc pnl balances for vaults with boost txs
  src/features/data/reducers/analytics.ts
  src/features/data/selectors/analytics.ts
Labels: ux-ok

#1845 update bluechips list
  src/helpers/utils.tsx
Labels: ux-ok

#1848 Update : Treasury summary stats
  src/features/data/selectors/treasury.ts
Labels: ux-ok

#1849 add wsteth-velo v2
  src/config/vault/optimism.json
Labels: vault-pr

#1856 Add 4 Synthetix ecosystem boosts + 2 partners info
  src/config/boost/optimism.json
  src/config/boost/partners.json
Labels: boost-pr

#1857 add aero axluscdeth
  src/config/vault/base.json
Labels: vault-pr

#1844 Update: new tech loader
  src/images/tech-loader.gif
Labels: ux-ok

#1859 EOL 4 Vaults Rewards, 3 Vaults Platform TVL
  src/config/vault/arbitrum.json
  src/config/vault/base.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
  src/config/vault/zkevm.json
Labels: vault-pr

#1858 Add Hop MAGIC & rETH
  src/config/vault/arbitrum.json
  src/images/single-assets/hMAGIC.svg
  src/images/single-assets/hrETH.svg
Labels: vault-pr

#1805 upgrade balancer arb/op through aura
  src/config/vault/arbitrum.json
  src/config/vault/optimism.json
Labels: vault-pr

#1865 disable thena-gamma-bnb-rbnb zap
  src/config/vault/bsc.json
Labels: ux-ok

#1867 Update hyUSD logo
  src/images/single-assets/hyUSD.svg
Labels: ux-ok

#1871 fix analytics shares address key
  src/features/data/selectors/analytics.ts
Labels: ux-ok

#1872 Update: Metis logo
  src/components/VaultIdentity/styles.ts
  src/features/treasury/components/DaoHoldings/components/ChainHolding/styles.tsx
  src/images/networks/metis.svg
  src/images/single-assets/METIS.svg
Labels: ux-ok

#1873 Update: remove cardHeader variable from theme
  src/components/Step/styles.tsx
  src/features/vault/components/BoostCard/styles.tsx
  src/features/vault/components/Card/CardHeader/styles.tsx
  src/features/vault/components/Card/CardTabs/styles.tsx
  src/features/vault/components/PnLGraph/components/Header/styles.tsx
  src/features/vault/components/VaultsStats/styles.tsx
  src/theme.ts
  src/types/@material-ui/core/index.d.ts
Labels: ux-ok
