Repository beefyfinance/beefy-v2, pull requests merged in 2023-05, with the labels that each got.

#1467 Add SoliSnek
  src/config/amm/avax.json
  src/config/platforms.json
  src/config/vault/avax.json
  src/config/zap/beefy.json
  src/config/zap/one-inch.json
Labels: vault-pr

#1469 Add RAM pairs
  src/config/vault/arbitrum.json
Labels: vault-pr

#1475 Unpause 6 Thena Vaults
  src/config/vault/bsc.json
Labels: vault-pr

#1474 [UPDATE] merge wnative to native exposure
  src/config/config.tsx
  src/features/data/selectors/balance.ts
  src/features/data/selectors/tokens.ts
  src/features/data/selectors/treasury.ts
Labels: ux-ok

#1476 [UPDATE] New Saved Vaults banner
  src/components/Banners/AnnouncementBanner/AnnouncementBanner.tsx
Labels: ux-ok

#1471 Fix: data dashboard crash when missing prices
  src/features/dashboard/components/UserVaults/components/VaultTransactions/VaultTransactions.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/Transaction.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/hook.tsx
  src/features/data/apis/amm/SolidlyPool.ts
  src/features/data/apis/amm/UniswapV2Pool.ts
  src/features/data/entities/analytics.ts
  src/features/vault/components/PnLGraph/hooks.tsx
  src/helpers/format.ts
  src/helpers/timeserie.ts
Labels: ux-ok

#1478 [UPDATE] Treasury page Logic
  src/features/data/actions/treasury.ts
  src/features/data/reducers/treasury.ts
  src/features/data/selectors/tokens.ts
  src/features/treasury/components/ExposureBar/styles.tsx
  src/features/treasury/components/ExposureChart/styles.tsx
  src/features/treasury/components/ExposureLegend/styles.tsx
  src/features/treasury/treasury.tsx
  src/locales/en/main.json
Labels: ux-ok

#1485 Reduce bsc min gas price to 3 gwei
  src/config/config.tsx
Labels: ux-ok

#1489 Add Velocimeter sCANTO vLPs
  src/config/vault/canto.json
  src/images/single-assets/BLOTR.png
  src/images/single-assets/sCANTO.webp
Labels: vault-pr

#1483 [UPDATE] add pnl graph on dashboard
  src/features/dashboard/components/UserVaults/components/MobileCollapseContent/MobileCollapseContent.tsx
  src/features/dashboard/components/UserVaults/components/Vault/Vault.tsx
  src/features/dashboard/components/UserVaults/components/Vault/styles.tsx
  src/features/data/selectors/analytics.ts
  src/features/vault/components/PnLGraph/PnLGraph.tsx
  src/features/vault/components/PnLGraph/components/Footer/Footer.tsx
  src/features/vault/components/PnLGraph/styles.tsx
  src/locales/en/main.json
Labels: ux-ok

#1492 [UPDATE] stablecoins lists
  src/config/config.tsx
  src/config/vault/arbitrum.json
  src/config/vault/avax.json
  src/config/vault/fantom.json
Labels: ux-ok, vault-pr

#1496 proxy 1inch requests via our api
  src/features/data/apis/one-inch/one-inch.ts
Labels: ux-ok

#1495 FIX: Apy's layout on Strategy Card
  src/features/vault/components/StrategyCard/styles.tsx
Labels: ux-ok
