Repository beefyfinance/beefy-v2, pull requests merged in 2024-04, with the labels that each got.

#2040 Update/deposit-withdraw flow
  src/components/SearchableList/Item.tsx
  src/components/SearchableList/SearchableList.tsx
  src/components/SearchableList/styles.tsx
  src/components/TokenAmount/TokenAmount.tsx
  src/components/TokenAmount/styles.ts
  src/features/bridge/components/Bridge/components/AmountSelector/AmountSelector.tsx
  src/features/bridge/components/Bridge/components/AmountSelector/styles.tsx
  src/features/bridge/components/Bridge/components/BalanceEndAdornment/BalanceEndAdornment.tsx
  src/features/bridge/components/Bridge/components/BalanceEndAdornment/index.tsx
  src/features/bridge/components/Bridge/components/BalanceEndAdornment/styles.tsx
  src/features/bridge/components/Bridge/components/SelectFromChainStep/SelectFromChainStep.tsx
  src/features/data/reducers/wallet/transact-types.ts
  src/features/data/reducers/wallet/transact.ts
  src/features/data/selectors/transact.ts
  src/features/vault/components/Actions/Transact/AmountInput/AmountInput.tsx
  src/features/vault/components/Actions/Transact/AmountInput/styles.tsx
  src/features/vault/components/Actions/Transact/AmountInputWithSlider/AmountInputWithSlider.tsx
  src/features/vault/components/Actions/Transact/AmountInputWithSlider/index.ts
  src/features/vault/components/Actions/Transact/AmountInputWithSlider/styles.tsx
  src/features/vault/components/Actions/Transact/CommonActions/CommonActions.tsx
  src/features/vault/components/Actions/Transact/DepositActions/DepositActions.tsx
  src/features/vault/components/Actions/Transact/DepositActions/styles.ts
  src/features/vault/components/Actions/Transact/DepositBuyLinks/DepositBuyLinks.tsx
  src/features/vault/components/Actions/Transact/DepositForm/DepositForm.tsx
  src/features/vault/components/Actions/Transact/DepositForm/styles.tsx
  src/features/vault/components/Actions/Transact/DepositTokenAmountInput/DepositTokenAmountInput.tsx
  src/features/vault/components/Actions/Transact/DepositTokenAmountInput/styles.tsx
  src/features/vault/components/Actions/Transact/TokenAmountIcon/TokenAmountIcon.tsx
  src/features/vault/components/Actions/Transact/TokenSelectButton/TokenSelectButton.tsx
  src/features/vault/components/Actions/Transact/TokenSelectButton/styles.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/DepositTokenSelectList.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/WithdrawTokenSelectList.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/styles.tsx
  src/features/vault/components/Actions/Transact/TokenSelectStep/TokenSelectStep.tsx
  src/features/vault/components/Actions/Transact/TransactQuote/TransactQuote.tsx
  src/features/vault/components/Actions/Transact/TransactQuote/styles.ts
  src/features/vault/components/Actions/Transact/VaultFees/Label.tsx
  src/features/vault/components/Actions/Transact/VaultFees/VaultFees.tsx
  src/features/vault/components/Actions/Transact/VaultFees/styles.ts
  src/features/vault/components/Actions/Transact/WithDrawLinks/WithdrawLinks.tsx
  src/features/vault/components/Actions/Transact/WithDrawLinks/index.ts
  src/features/vault/components/Actions/Transact/WithDrawLinks/styles.ts
  src/features/vault/components/Actions/Transact/WithdrawActions/WithdrawActions.tsx
  src/features/vault/components/Actions/Transact/WithdrawActions/styles.ts
  src/features/vault/components/Actions/Transact/WithdrawForm/WithdrawForm.tsx
  src/features/vault/components/Actions/Transact/WithdrawForm/styles.tsx
  src/features/vault/components/Actions/Transact/WithdrawTokenAmountInput/WithdrawTokenAmountInput.tsx
  src/features/vault/components/Actions/Transact/WithdrawTokenAmountInput/styles.tsx
  src/images/icons/build-lp.svg
  src/locales/en/main.json
  src/locales/zh/main.json
Labels: ux-ok, code-ok

#2084 2 dp for BIFI nav price
  src/components/Header/components/Prices/Prices.tsx
  src/helpers/format.ts
Labels: ux-ok

#2089 Round performance fee to 2dp
  src/features/vault/components/Actions/Transact/VaultFees/PerformanceFees.tsx
  src/helpers/format.ts
Labels: ux-ok

#2092 Add Aerodrome RSR-bsdETH vLP
  src/config/vault/base.json
  src/images/single-assets/RSR.svg
Labels: don't merge

#2090 Update blocknative + axelar sdk
  package.json
  src/features/data/apis/axelar/axelar.ts
  src/features/data/apis/wallet/wallet-connection.ts
  yarn.lock
Labels: ux-ok

#2091 Update: styles historical rate
  src/features/vault/components/HistoricGraph/CowcentratedRanges/CowcentratedRanges.tsx
  src/features/vault/components/HistoricGraph/CowcentratedRanges/index.tsx
  src/features/vault/components/HistoricGraph/CowcentratedRanges/styles.tsx
  src/features/vault/components/HistoricGraph/Graph/Graph.tsx
  src/features/vault/components/HistoricGraph/HistoricGraphs.tsx
  src/features/vault/components/HistoricGraph/StatSwitcher/StatSwitcher.tsx
  src/features/vault/components/HistoricGraph/StatSwitcher/styles.tsx
  src/features/vault/components/HistoricGraph/styles.tsx
Labels: ux-ok

#2106 Update/ ETH-->WETH on clm names
  src/config/vault/arbitrum.json
Labels: ux-ok

#2109 fix some linea zap-outs + quote loop
  src/config/vault/linea.json
  src/features/data/actions/transact.ts
  src/features/vault/components/Actions/Transact/TransactQuote/TransactQuote.tsx
Labels: ux-ok

#2119 Discord link .com->.finance
  src/components/Footer/Footer.tsx
  src/features/vault/components/CLMBanner/CLMBanner.tsx
Labels: ux-ok

#2131 Add 4 Optimism boosts
  src/config/boost/optimism.json
Labels: boost-pr
