Repository beefyfinance/beefy-v2, pull requests merged in 2024-08, with the labels that each got.

#2312 Update/ Account for boost apys in daily stats
  src/components/VaultStats/VaultDailyUsdStat.tsx
  src/features/dashboard/components/UserVaults/components/TabletStats/TabletStats.tsx
  src/features/data/selectors/apy.ts
Labels: ux-ok

#2323 Update/ Points for some mETH vaults
  src/config/vault/mantle.json
Labels: ux-ok

#2337 Update/ Standard pnl graph styles
  package.json
  src/features/vault/components/HistoricGraph/RangeSwitcher/styles.tsx
  src/features/vault/components/PnLGraph/cowcentrated/components/Footers/styles.tsx
  src/features/vault/components/PnLGraph/standard/StandardPnLGraph.tsx
  src/features/vault/components/PnLGraph/standard/components/Footer/styles.tsx
  src/features/vault/components/PnLGraph/standard/components/Header/Header.tsx
  src/features/vault/components/PnLGraph/standard/components/Header/styles.tsx
  src/features/vault/components/PnLGraph/standard/components/PnLTooltip/PnLTooltip.tsx
  src/features/vault/components/PnLGraph/standard/styles.tsx
  yarn.lock
Labels: ux-ok

#2335 Update/ eol fuse
  src/config/config.tsx
  src/config/vault/fuse.json
  src/features/data/apis/config-types.ts
  src/features/data/apis/config.ts
  src/features/data/reducers/partners.ts
  src/features/data/selectors/partners.ts
  src/features/vault/components/InsuranceCards/InsuranceCards.tsx
  src/helpers/partners.tsx
Labels: ux-ok

#2352 Feat/PoolTogether Widget
  src/config/vault/base.json
  src/config/vault/optimism.json
  src/features/data/actions/vaults.ts
  src/features/data/apis/config-types.ts
  src/features/data/entities/vault.ts
  src/features/data/selectors/partners.ts
  src/features/vault/components/GamingCards/GamingCards.tsx
  src/features/vault/components/GamingCards/index.tsx
  src/features/vault/components/GamingCards/styles.tsx
  src/features/vault/components/PoolTogetherCard/index.tsx
  src/features/vault/vault.tsx
  src/images/partners/pooltogether.svg
  src/locales/en/main.json
Labels: ux-ok

#2355 Update/ Add footer divider line for dashboard standard PnL graph
  src/features/vault/components/PnLGraph/standard/StandardPnLGraph.tsx
  src/features/vault/components/PnLGraph/standard/components/Footer/Footer.tsx
  src/features/vault/components/PnLGraph/standard/styles.tsx
Labels: ux-ok

#2343 Add boost contract link
  src/features/vault/components/BoostCard/BoostCard.tsx
  src/features/vault/components/BoostCard/styles.tsx
  src/locales/en/main.json
Labels: don't merge

#2365 Add Aerodrome and Velodrome vaults
  src/config/vault/base.json
  src/config/vault/optimism.json
Labels: vault-pr

#2373 Update/Add Analytics to resources
  src/components/Header/list.tsx
  src/images/icons/navigation/analytics.svg
  src/locales/en/main.json
Labels: ux-ok

#2370 use vault id for lp breakdown/underlying tvl when oracle is tokens
  src/features/data/actions/vaults.ts
  src/features/data/entities/vault.ts
  src/features/data/reducers/analytics-types.ts
  src/features/data/selectors/balance.ts
  src/features/data/selectors/tokens.ts
  src/features/data/selectors/vaults.ts
  src/features/vault/components/LiquidityPoolBreakdown/LiquidityPoolBreakdown.tsx
  src/features/vault/components/PnLGraph/cowcentrated/CowcentratedPnlGraph.tsx
Labels: ux-ok
