Repository beefyfinance/beefy-v2, pull requests merged in 2024-05, with the labels that each got.

#2138 Update stables02052024
  package.json
  src/config/config.tsx
  src/images/single-assets/aaUSDC.svg
  yarn.lock
Labels: ux-ok

#2135 Add merkl claimer module to clm vaults
  src/components/AssetsImage/AssetsImage.tsx
  src/components/AssetsImage/styles.tsx
  src/config/abi/AngleMerklDistributor.ts
  src/features/data/actions/rewards.ts
  src/features/data/actions/scenarios.ts
  src/features/data/actions/wallet-actions.tsx
  src/features/data/apis/instances.ts
  src/features/data/apis/rewards/merkl/merkl-api.ts
  src/features/data/apis/rewards/merkl/merkl-types.ts
  src/features/data/apis/transact/strategies/IStrategy.ts
  src/features/data/middlewares/wallet.ts
  src/features/data/reducers/index.tsx
  src/features/data/reducers/wallet/rewards.ts
  src/features/data/reducers/wallet/stepper.ts
  src/features/data/selectors/rewards.ts
  src/features/vault/components/Actions/Actions.tsx
  src/features/vault/components/Actions/Rewards/Merkl/Claim/Claim.tsx
  src/features/vault/components/Actions/Rewards/Merkl/Merkl.tsx
  src/features/vault/components/Actions/Rewards/Merkl/RewardList/RewardList.tsx
  src/features/vault/components/Actions/Rewards/Merkl/RewardList/styles.tsx
  src/features/vault/components/Actions/Rewards/Merkl/styles.tsx
  src/images/partners/merkl.svg
  src/images/single-assets/missing-asset.svg
  src/locales/en/main.json
  src/redux-types.ts
  src/store.ts
Labels: ux-ok

#2136 Feat/ Underlying breakdown for clm's
  src/features/data/selectors/balance.ts
  src/features/vault/components/HistoricGraph/HistoricGraphs.tsx
  src/features/vault/components/LiquidityPoolBreakdown/LiquidityPoolBreakdown.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Chart/Chart.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/ChartWithLegend/ChartWithLegend.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Legend/Legend.tsx
  src/features/vault/components/LiquidityPoolBreakdown/hooks.tsx
  src/features/vault/components/LiquidityPoolBreakdown/styles.tsx
  src/features/vault/components/LiquidityPoolBreakdown/types.ts
  src/features/vault/components/StatSwitcher/StatSwitcher.tsx
  src/features/vault/components/StatSwitcher/index.tsx
  src/features/vault/components/StatSwitcher/styles.tsx
  src/locales/en/main.json
Labels: ux-ok

#2142 Add Thena Gamma vaults
  src/config/vault/bsc.json
Labels: vault-pr

#2143 Add ETH (ezETH Market) Boost
  src/config/boost/arbitrum.json
Labels: boost-pr

#2123 main position graph
  src/features/data/actions/historical.ts
  src/features/data/apis/beefy/beefy-data-api-types.ts
  src/features/data/apis/beefy/beefy-data-api.ts
  src/features/data/reducers/historical-types.ts
  src/features/data/reducers/historical.ts
  src/features/data/selectors/historical.ts
  src/features/data/selectors/tokens.ts
  src/features/vault/components/HistoricGraph/CowcentratedRanges/CowcentratedRanges.tsx
  src/features/vault/components/HistoricGraph/CowcentratedRanges/styles.tsx
  src/features/vault/components/HistoricGraph/Graph/Graph.tsx
  src/features/vault/components/HistoricGraph/Graph/useChartData.tsx
  src/features/vault/components/HistoricGraph/GraphWithControls/GraphWithControls.tsx
  src/features/vault/components/HistoricGraph/GraphWithControls/styles.tsx
  src/features/vault/components/HistoricGraph/HistoricGraphs.tsx
  src/features/vault/components/HistoricGraph/TooltipContent/TooltipContent.tsx
  src/features/vault/components/HistoricGraph/TooltipContent/styles.tsx
  src/features/vault/components/HistoricGraph/styles.tsx
  src/locales/en/main.json
Labels: ux-ok

#2149 EOL Moonriver
  src/config/config.tsx
  src/config/vault/moonriver.json
Labels: ux-ok

#2156 Mode Velodrome Zap
  src/config/vault/mode.json
  src/config/zap/amm/mode.json
  src/features/data/apis/amm/index.ts
  src/features/data/apis/amm/solidly/VelodromeV2ModeSolidlyPool.ts
Labels: ux-ok

#2160 Update/ reenable opencover for clm's
  src/features/data/selectors/partners.ts
  src/features/vault/components/InsuranceCards/InsuranceCards.tsx
  src/features/vault/components/OpenCoverCard/index.tsx
Labels: ux-ok, code-ok
