Repository beefyfinance/beefy-v2, pull requests merged in 2024-02, with the labels that each got.

#1952 add-aero-usdc+-usd+
  src/config/boost/optimism.json
  src/config/vault/base.json
  src/images/single-assets/base/USDC+.svg
Labels: vault-pr

#1959 Feat/wormhole bridge
  src/components/ApyStats/ApyStats.tsx
  src/components/LinkButton/LinkButton.tsx
  src/components/TechLoader/TechLoader.tsx
  src/components/VaultIdentity/VaultIdentity.tsx
  src/components/VaultIdentity/components/VaultTags/VaultTags.tsx
  src/components/VaultStats/VaultDailyStat.tsx
  src/components/VaultStats/VaultYearlyStat.tsx
  src/features/data/actions/balance.ts
  src/features/data/reducers/wallet/balance.ts
  src/features/data/selectors/apy.ts
  src/features/data/selectors/balance.ts
  src/features/data/selectors/filtered-vaults.ts
  src/features/vault/components/Actions/Transact/DepositForm/DepositForm.tsx
  src/features/vault/components/AddTokenToWallet/RewardTokenDetails.tsx
  src/features/vault/components/WormholeBridge/WormholeBridge.tsx
  src/features/vault/components/WormholeBridge/WormholeModal.tsx
  src/features/vault/components/WormholeBridge/styles.tsx
  src/features/vault/vault.tsx
Labels: ux-ok

#1968 Add Fantom Menace vault
  src/config/vault/fantom.json
Labels: vault-pr

#1976 Feat/vault no safu warning
  package.json
  src/config/risk.tsx
  src/config/vault/ethereum.json
  src/features/data/apis/addressbook.ts
  src/features/data/apis/config-types.ts
  src/features/data/entities/platform.ts
  src/features/data/entities/token.ts
  src/features/data/reducers/platforms.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/tokens.ts
  src/features/data/selectors/vaults.ts
  src/features/vault/components/Actions/Actions.tsx
  src/features/vault/components/Card/Card.tsx
  src/features/vault/components/NoSafuRisks/NoSafuRisks.tsx
  src/features/vault/components/NoSafuRisks/index.tsx
  src/features/vault/components/NoSafuRisks/styles.tsx
  src/features/vault/components/SafetyCard/SafetyCard.tsx
  src/features/vault/components/SafetyCard/styles.tsx
  src/images/single-assets/ezETH.png
  src/images/single-assets/weETH.png
  src/locales/en/risks.json
  yarn.lock
Labels: ux-ok, code-ok

#1978 Update/ USDC.e vault names on polygon
  src/config/vault/polygon.json
Labels: ux-ok, code-ok

#1948 Feat: Let users input numbers above balance
  src/features/bridge/components/Bridge/components/AmountSelector/AmountSelector.tsx
  src/features/bridge/components/Bridge/components/Preview/Preview.tsx
  src/features/data/actions/bridge.ts
  src/features/data/apis/transact/helpers/vault.ts
  src/features/data/selectors/transact.ts
  src/features/vault/components/Actions/Transact/AmountInput/AmountInput.tsx
  src/features/vault/components/Actions/Transact/AmountInput/styles.tsx
  src/features/vault/components/Actions/Transact/DepositActions/DepositActions.tsx
  src/features/vault/components/Actions/Transact/DepositTokenAmountInput/DepositTokenAmountInput.tsx
  src/features/vault/components/Actions/Transact/WithdrawActions/WithdrawActions.tsx
  src/features/vault/components/Actions/Transact/WithdrawTokenAmountInput/WithdrawTokenAmountInput.tsx
  src/locales/en/main.json
Labels: ux-ok, code-ok

#1979 point to correct pool
  src/config/vault/polygon.json
Labels: ux-ok

#1980 update sFTMx logo
  src/images/single-assets/sFTMx.png
Labels: ux-ok

#1983 Update/ Show arb compound usdc with boosts filter
  src/features/data/selectors/filtered-vaults.ts
Labels: ux-ok, code-ok

#1986 change MIM to abracadabra, update belt strategy types, edit lendingNo…
  src/config/platforms.json
  src/config/vault/arbitrum.json
  src/config/vault/avax.json
  src/config/vault/bsc.json
  src/config/vault/fantom.json
  src/locales/en/risks.json
Labels: ux-ok, code-ok

#1987 Update/ Optimism stables and remove new from mantle chain
  src/config/config.tsx
Labels: ux-ok, code-ok

#1984 EOL QuickSwap Gamma vaults which will not harvest
  src/config/vault/arbitrum.json
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/ethereum.json
  src/config/vault/metis.json
  src/config/vault/polygon.json
Labels: vault-pr

#1988 Add Curve to partners, add crvUSD/sUSD and crvUSD/USDC boosts
  src/config/boost/optimism.json
  src/config/boost/partners.json
Labels: boost-pr

#1985 Fix missing lp breakdown when one token has zero balance
  src/features/data/reducers/tokens.ts
Labels: ux-ok

#1964 Support multi lines token description
  src/features/vault/components/TokenCard/styles.tsx
Labels: ux-ok, code-ok

#1990 Update curve urls
  scripts/addCurveZap.ts
  scripts/common/utils.ts
  scripts/setVaultUrls.ts
  src/config/vault/arbitrum.json
  src/config/vault/avax.json
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/celo.json
  src/config/vault/ethereum.json
  src/config/vault/fantom.json
  src/config/vault/fuse.json
  src/config/vault/kava.json
  src/config/vault/moonbeam.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
Labels: ux-ok, code-ok

#1982 Update/ handle tokens and platform risks at the same time
  src/config/risk.tsx
  src/features/data/reducers/platforms.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/vaults.ts
  src/features/vault/components/NoSafuRisks/NoSafuRisks.tsx
  src/features/vault/components/NoSafuRisks/hooks.tsx
  src/locales/en/risks.json
Labels: ux-ok, code-ok

#1969 Update: Onramp token list offer
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/on-ramp.ts
  src/features/on-ramp/components/OnRamp/components/InjectProviderStep/ProviderFrame.tsx
  src/features/on-ramp/components/OnRamp/components/InjectProviderStep/styles.tsx
  src/features/on-ramp/components/OnRamp/components/TokenStep/TokenStep.tsx
  src/images/single-assets/XDAI.svg
Labels: ux-ok, code-ok

#1977 Feat: Gamma zap
  src/config/abi/gammaHypervisor.json
  src/config/abi/gammaProxy.json
  src/config/abi/index.ts
  src/config/abi/uniswapV3Pool.json
  src/config/vault/arbitrum.json
  src/config/vault/base.json
  src/config/vault/bsc.json
  src/config/vault/ethereum.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
  src/config/vault/zkevm.json
  src/config/zap/amm/arbitrum.json
  src/config/zap/amm/base.json
  src/config/zap/amm/bsc.json
  src/config/zap/amm/ethereum.json
  src/config/zap/amm/moonbeam.json
  src/config/zap/amm/optimism.json
  src/config/zap/amm/polygon.json
  src/config/zap/amm/zkevm.json
  src/features/data/actions/wallet-actions.tsx
  src/features/data/apis/amm/gamma/GammaPool.ts
  src/features/data/apis/amm/gamma/TickMath.ts
  src/features/data/apis/amm/helpers.ts
  src/features/data/apis/amm/types.ts
  src/features/data/apis/config-types.ts
  src/features/data/apis/transact/helpers/amounts.ts
  src/features/data/apis/transact/helpers/quotes.ts
  src/features/data/apis/transact/strategies/IStrategy.ts
  src/features/data/apis/transact/strategies/UniswapLikeStrategy.ts
  src/features/data/apis/transact/strategies/gamma/GammaStrategy.ts
  src/features/data/apis/transact/strategies/index.ts
  src/features/data/apis/transact/transact-types.ts
  src/features/data/entities/zap.ts
  src/features/data/reducers/wallet/transact.ts
  src/features/data/reducers/wallet/wallet-action.ts
  src/features/data/selectors/transact.ts
  src/features/vault/components/Actions/Transact/CommonActions/CommonActions.tsx
  src/features/vault/components/Actions/Transact/DepositActions/DepositActions.tsx
  src/features/vault/components/Actions/Transact/NotEnoughNotice/NotEnoughNotice.tsx
  src/features/vault/components/Actions/Transact/NotEnoughNotice/index.tsx
  src/features/vault/components/Actions/Transact/PriceImpactNotice/PriceImpactNotice.tsx
  src/features/vault/components/Actions/Transact/WithdrawActions/WithdrawActions.tsx
  src/helpers/big-number.ts
  src/locales/en/main.json
Labels: ux-ok

#1992 add velodrome vaults
  src/config/vault/optimism.json
Labels: vault-pr

#1994 beQI v2
  package.json
  src/components/TokenImage/TokenImage.tsx
  src/config/minters/avax.tsx
  src/config/minters/ethereum.tsx
  src/config/minters/fantom.tsx
  src/config/minters/optimism.tsx
  src/config/minters/polygon.tsx
  src/config/vault/ethereum.json
  src/config/vault/polygon.json
  src/features/data/apis/config-types.ts
  src/features/data/selectors/minters.ts
  src/features/vault/components/Actions/Minter/MintBurnCard/components/Mint.tsx
  src/features/vault/components/Actions/Minter/MinterCard.tsx
  src/images/single-assets/QI BPT.svg
  src/locales/en/main.json
  src/locales/en/risks.json
  yarn.lock
Labels: ux-ok

#1995 Add token in wallet notice on withdraw tab
  src/components/Alerts/index.tsx
  src/components/Alerts/styles.ts
  src/features/vault/components/Actions/Transact/WithdrawForm/WithdrawForm.tsx
  src/features/vault/components/Actions/Transact/WithdrawForm/styles.tsx
  src/features/vault/components/Actions/Transact/WithdrawnInWalletNotice/WithdrawnInWalletNotice.tsx
  src/features/vault/components/Actions/Transact/WithdrawnInWalletNotice/index.tsx
  src/features/vault/components/Actions/Transact/WithdrawnInWalletNotice/styles.ts
  src/locales/en/main.json
  src/theme.ts
  src/types/@material-ui/core/index.d.ts
Labels: ux-ok

#1997 Add SILO token, Add Silo partner, add ETH boost
  src/config/boost/ethereum.json
  src/config/boost/partners.json
  src/images/single-assets/ethereum/SILO.svg
Labels: boost-pr

#2003 Add VEC, Vector Reserve partner, vETH-ETH Boost
  src/config/boost/ethereum.json
  src/config/boost/partners.json
  src/images/single-assets/ethereum/VEC.svg
Labels: boost-pr
