Repository beefyfinance/beefy-v2, pull requests merged in 2024-07, with the labels that each got.

#2240 Update/ My filter text
  src/locales/en/main.json
Labels: ux-ok

#2241 add points for camelot-ezeth-weth
  src/config/vault/arbitrum.json
Labels: ux-ok

#2242 upgrade aura 4pool and wsteth-eth vaults to handle arb rewards
  src/config/vault/arbitrum.json
Labels: vault-pr

#2234 Add ETH-rETH stable vault on Aerodrome Base
  scripts/getPoolCreationTimestamp.ts
  src/config/vault/base.json
Labels: vault-pr

#2238 add aura frax-symphony and wmatic-maticx pools
  src/config/vault/base.json
  src/config/vault/optimism.json
  src/config/vault/polygon.json
Labels: vault-pr

#2243 add new balancer vaults
  src/config/vault/arbitrum.json
  src/config/vault/polygon.json
Labels: vault-pr

#2252 Mark CLM Pools as not having zap if no aggregator available for chain…
  src/features/data/actions/zap.ts
  src/features/data/apis/transact/transact.ts
  src/features/data/reducers/zaps.ts
  src/features/data/selectors/zap.ts
Labels: ux-ok

#2253 update unstaked clm banner text
  src/locales/en/main.json
Labels: ux-ok

#2254 Change current cowcentrated ranges load condition
  src/features/data/actions/historical.ts
  src/features/data/actions/tokens.ts
  src/features/data/entities/token.ts
  src/features/data/reducers/data-loader-types.ts
  src/features/data/reducers/data-loader.ts
  src/features/data/reducers/historical.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/analytics.ts
  src/features/data/selectors/data-loader.ts
  src/features/data/selectors/tokens.ts
  src/features/vault/components/HistoricGraph/CowcentratedRanges/index.tsx
  src/features/vault/components/HistoricGraph/CurrentCowcentratedRange/CurrentCowcentratedRange.tsx
  src/features/vault/components/HistoricGraph/CurrentCowcentratedRange/index.tsx
  src/features/vault/components/HistoricGraph/CurrentCowcentratedRange/styles.tsx
  src/features/vault/components/HistoricGraph/HistoricGraphs.tsx
  src/features/vault/components/HistoricGraph/HistoricGraphsLoader.tsx
Labels: ux-ok

#2251 Dashboard clm exposure fix
  package.json
  src/features/dashboard/components/ChainExposure/index.tsx
  src/features/dashboard/components/PlatformExposure/index.tsx
  src/features/dashboard/components/StablesExposure/StablesExposure.tsx
  src/features/dashboard/components/TokenExposure/index.tsx
  src/features/dashboard/components/UserVaults/hook.tsx
  src/features/data/apis/transact/transact.ts
  src/features/data/selectors/apy.ts
  src/features/data/selectors/balance.ts
Labels: ux-ok

#2267 Update/ search to exclude gov clm's from reward tokens search
  src/features/data/selectors/filtered-vaults.ts
Labels: ux-ok

#2269 allow claim merkl vault rewards for other chains
  package.json
  src/components/Button/styles.ts
  src/components/Stepper/components/TransactionLink/TransactionLink.tsx
  src/features/data/actions/apy.ts
  src/features/data/actions/user-rewards-types.ts
  src/features/data/actions/user-rewards.ts
  src/features/data/actions/wallet-actions.tsx
  src/features/data/apis/beefy/beefy-api-types.ts
  src/features/data/apis/beefy/beefy-api.ts
  src/features/data/apis/migration/index.ts
  src/features/data/apis/rewards/merkl/merkl-api.ts
  src/features/data/apis/rewards/merkl/merkl-types.ts
  src/features/data/middlewares/transact.ts
  src/features/data/reducers/chains.ts
  src/features/data/reducers/data-loader-types.ts
  src/features/data/reducers/data-loader.ts
  src/features/data/reducers/wallet/migration.ts
  src/features/data/reducers/wallet/user-rewards-types.ts
  src/features/data/reducers/wallet/user-rewards.ts
  src/features/data/selectors/balance.ts
  src/features/data/selectors/chains.ts
  src/features/data/selectors/data-loader-helpers.ts
  src/features/data/selectors/data-loader.ts
  src/features/data/selectors/migration.ts
  src/features/data/selectors/rewards.ts
  src/features/data/selectors/transact.ts
  src/features/data/selectors/treasury.ts
  src/features/data/selectors/user-rewards.ts
  src/features/vault/components/Actions/Transact/ClaimForm/Gov/Claim/Claim.tsx
  src/features/vault/components/Actions/Transact/ClaimForm/Gov/GovRewards.tsx
  src/features/vault/components/Actions/Transact/ClaimForm/Merkl/Claim/Claim.tsx
  src/features/vault/components/Actions/Transact/ClaimForm/Merkl/Claim/styles.tsx
  src/features/vault/components/Actions/Transact/ClaimForm/Merkl/MerklRewards.tsx
  src/features/vault/components/Actions/Transact/ClaimForm/RewardList/RewardList.tsx
  src/features/vault/components/Actions/Transact/CommonActions/CommonActions.tsx
  src/features/vault/components/Actions/Transact/FormStep/FormStep.tsx
  src/features/vault/components/Card/CardTabs/CardTabs.tsx
  src/features/vault/components/Card/CardTabs/styles.tsx
  src/locales/en/main.json
  src/redux-types.ts
  yarn.lock
Labels: ux-ok

#2169 Add Curve/Convex TriCRV vault.
  src/config/vault/ethereum.json
Labels: don't merge

#2262 move gyro-arb-wsteth-weth vault to aura
  src/config/vault/arbitrum.json
Labels: vault-pr

#2285 add Shezmu boosts
  src/config/boost/ethereum.json
  src/config/boost/partners.json
  src/images/single-assets/ethereum/SHEZMU.png
Labels: boost-pr

#2287 Add ETH-TLX
  src/config/vault/optimism.json
  src/images/single-assets/TLX.png
Labels: vault-pr

#2283 Add aero USDz sUSDz
  src/config/config.tsx
  src/config/vault/base.json
  src/images/single-assets/sUSDz.svg
Labels: vault-pr

#2289 fix perf fee not displaying for clm pools
  src/features/data/actions/fees.ts
  src/features/data/reducers/vaults.ts
  src/features/data/selectors/fees.ts
  src/features/data/selectors/vaults.ts
Labels: ux-ok

#2290 fix ramses pool tokens boost status
  src/features/data/actions/apy.ts
Labels: ux-ok

#2286 Update/ WalletContainer UX
  src/components/Header/components/ConnectionStatus/ConnectionStatus.tsx
  src/components/Header/components/WalletContainer/WalletContainer.tsx
Labels: ux-ok

#2292 Add Balancer boost wstETH-ETH
  src/config/boost/arbitrum.json
  src/config/boost/partners.json
Labels: boost-pr

#2302 TVL: clm base also exclude clm vault
  scripts/validatePools.ts
  src/features/data/actions/vaults.ts
  src/features/data/entities/vault.ts
  src/features/data/reducers/tvl.ts
Labels: ux-ok

#2311 remove bare CLM counting towards CLM Pool deposit/pnl
  src/components/Banners/Banner/Banner.tsx
  src/components/Banners/Banner/styles.tsx
  src/components/Banners/BusdBanner/BusdBanner.tsx
  src/components/Banners/Links/Links.tsx
  src/components/Banners/UnstakedClmBanner/UnstakedClmBanner.tsx
  src/components/VaultDepositedTooltip/VaultDepositedTooltip.tsx
  src/components/VaultDepositedTooltip/styles.ts
  src/components/VaultStats/VaultDepositStat.tsx
  src/components/VaultStats/VaultWalletStat.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/VaultTransactions.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/Transaction.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/Transaction/styles.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/components/TransactionTimelineSeparator/TransactionTimelineSeparator.tsx
  src/features/dashboard/components/UserVaults/components/VaultTransactions/hook.tsx
  src/features/data/actions/analytics.ts
  src/features/data/actions/user-rewards.ts
  src/features/data/apis/analytics/analytics-types.ts
  src/features/data/apis/analytics/analytics.ts
  src/features/data/entities/analytics.ts
  src/features/data/reducers/analytics.ts
  src/features/data/selectors/analytics.ts
  src/features/data/selectors/apy.ts
  src/features/data/selectors/balance.ts
  src/features/data/utils/types-utils.ts
  src/features/vault/components/DisplacedBalances/DisplacedBalances.tsx
  src/features/vault/components/PnLGraph/cowcentrated/components/OverviewGraph/hooks.tsx
  src/features/vault/components/PnLGraph/standard/hooks.tsx
  src/helpers/timeserie.ts
  src/locales/en/main.json
Labels: ux-ok

#2295 upgrade balancer-arb-usdc-gusdc
  src/config/vault/arbitrum.json
Labels: vault-pr

#2121 Prepare Lynex USDC-DUSD LP vault
  src/config/config.tsx
  src/config/vault/linea.json
  src/images/single-assets/DUSD.png
Labels: vault-pr
