Repository beefyfinance/beefy-v2, pull requests merged in 2024-10, with the labels that each got.

#2425 base moobifi bridge
  package.json
  src/components/Header/components/Prices/Prices.tsx
  src/components/Header/components/Prices/styles.tsx
  src/config/beefy-bridge.ts
  src/config/boost/rootstock.json
  src/config/vault/ethereum.json
  src/features/data/apis/beefy/beefy-api.ts
  src/images/single-assets/DOC.svg
  src/images/single-assets/DOC.webp
  yarn.lock
Labels: ux-ok

#2428 Add velodrome and aerodrome vaults
  src/config/vault/base.json
  src/config/vault/optimism.json
Labels: vault-pr

#2427 Update/ migrate matic to pol
  scripts/common/addressbook.ts
  scripts/common/tokens.ts
  src/config/config.tsx
  src/config/vault/polygon.json
  src/features/data/apis/addressbook.ts
  src/features/data/apis/config-types.ts
  src/features/data/apis/viem/chains.ts
  src/features/data/apis/wallet/wallet-connection.ts
  src/features/data/reducers/tokens.ts
  src/features/data/selectors/chains.ts
  src/features/vault/components/Explainer/Description/common.tsx
  src/images/single-assets/POL.png
  src/images/single-assets/RBTC.svg
  src/images/single-assets/WPOL.png
  src/images/single-assets/WRBTC.svg
  src/images/single-assets/WRBTC.webp
Labels: ux-ok, changes requested

#2431 Feat/ add contracts dropdown
  src/features/data/selectors/boosts.ts
  src/features/vault/components/BoostCard/BoostCard.tsx
  src/features/vault/components/Explainer/ContractsDropdown/index.tsx
  src/features/vault/components/Explainer/Cowcentrated/CowcentratedExplainer.tsx
  src/features/vault/components/Explainer/ExplainerCard/ExplainerCard.tsx
  src/features/vault/components/Explainer/ExplainerCard/styles.tsx
  src/features/vault/components/Explainer/Gov/GovExplainer.tsx
  src/features/vault/components/Explainer/Standard/StandardExplainer.tsx
  src/locales/en/main.json
Labels: ux-ok

#2446 eol zkevm
  src/config/config.tsx
Labels: ux-ok

#2447 Update / remove logic for rewards token in search list
  src/features/data/selectors/filtered-vaults.ts
Labels: ux-ok, changes requested

#2453 Update Base Boost Pins
  src/config/boost/base.json
Labels: ux-ok

#2443 Feat/ Add LP/CLM tag
  src/features/data/selectors/transact.ts
  src/features/vault/components/Actions/Transact/TokenSelectList/DepositTokenSelectList.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/WithdrawTokenSelectList.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/components/ListItem/ListItem.tsx
  src/features/vault/components/Actions/Transact/TokenSelectList/components/ListItem/styles.tsx
  src/helpers/tokens.ts
Labels: ux-ok
