Repository beefyfinance/beefy-v2, pull requests merged in 2024-03, with the labels that each got.

#1998 Update : use token symbol as source for images
  src/components/AssetsImage/AssetsImage.tsx
  src/components/Banners/BusdBanner/BusdBanner.tsx
  src/components/PieChartTooltip/PieChartTooltip.tsx
  src/components/RewardsTooltip/RewardsTooltip.tsx
  src/components/TokenImage/TokenImage.tsx
  src/components/VaultIdentity/components/VaultIcon/VaultIcon.tsx
  src/features/data/selectors/tokens.ts
  src/features/data/selectors/treasury.ts
  src/features/on-ramp/components/OnRamp/components/TokenAmountAdornment/TokenAmountAdornment.tsx
  src/features/on-ramp/components/OnRamp/components/TokenStep/TokenStep.tsx
  src/features/on-ramp/components/OnRamp/components/TokenTitleAdornment/TokenIconAdornment.tsx
  src/features/treasury/components/DaoHoldings/components/AssetInfo/AssetInfo.tsx
  src/features/vault/components/Actions/Boosts/BoostPastActionCard/BoostPastActionCard.tsx
  src/features/vault/components/Actions/Minter/MintBurnCard/components/Burn.tsx
  src/features/vault/components/Actions/Minter/MintBurnCard/components/Mint.tsx
  src/features/vault/components/AddTokenToWallet/RewardTokenDetails.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/BreakdownTable/BreakdownTable.tsx
  src/features/vault/components/LiquidityPoolBreakdown/components/Legend/Legend.tsx
  src/features/vault/components/StrategyCard/StrategyDescription.tsx
  src/features/vault/components/TokenCard/TokenCard.tsx
  src/features/vault/components/TokenWithBalance/TokenWithBalance.tsx
  src/features/vault/components/TokenWithBalance/index.tsx
  src/features/vault/components/TokenWithBalance/styles.ts
  src/features/vault/components/TokenWithDeposit/TokenWithDeposit.tsx
  src/features/vault/components/TokenWithDeposit/index.tsx
  src/features/vault/components/TokenWithDeposit/styles.ts
  src/features/vault/components/VaultHeader/index.tsx
  src/images/single-assets/arbUSDCe.svg
  src/images/single-assets/beJOE.png
  src/images/single-assets/beQI.png
  src/images/single-assets/opUSDCe.svg
  src/images/single-assets/pUSDCe.svg
Labels: ux-ok, code-ok

#1999 Feat: Add onlyEarningPoints filter
  src/components/VaultIdentity/components/VaultTags/VaultTags.tsx
  src/components/VaultIdentity/components/VaultTags/styles.ts
  src/config/boost/ethereum.json
  src/config/vault/arbitrum.json
  src/config/vault/ethereum.json
  src/features/data/apis/config-types.ts
  src/features/data/entities/vault.ts
  src/features/data/reducers/filtered-vaults.ts
  src/features/data/reducers/vaults.ts
  src/features/data/selectors/filtered-vaults.ts
  src/features/home/components/Filters/components/ExtendedFilters/ExtendedFilters.tsx
  src/locales/en/main.json
Labels: ux-ok, code-ok

#2009 Update: onramp provider logos
  src/helpers/onrampProviderSrc.ts
  src/images/onramp-providers/icons/binance.svg
  src/images/onramp-providers/logos/binance.svg
  src/images/onramp-providers/logos/mtpelerin.svg
  src/images/onramp-providers/logos/transak.svg
Labels: ux-ok, code-ok

#2015 Fix: vault page tooltip position
  src/components/Popover/Popover.tsx
Labels: ux-ok

#2016 Add aerodrome tybg eth
  src/config/vault/base.json
  src/images/single-assets/TYBG.png
Labels: vault-pr

#2023 Add Velo USDC-LUSD and USDC-sUSD vaults
  src/config/vault/optimism.json
Labels: vault-pr

#2025 Add velodrome USDC vaults
  src/config/vault/optimism.json
Labels: vault-pr

#2031 Update: Wormhole extra apy
  src/features/data/selectors/apy.ts
Labels: ux-ok

#2041 add required iframe params to mtpelerin
  src/features/on-ramp/components/OnRamp/components/InjectProviderStep/ProviderFrame.tsx
Labels: code-ok

#2038 add aerodrome-weth-reth
  src/config/vault/base.json
Labels: vault-pr

#2034 Fix boost apy race + Move vaults filter results to state
  src/features/dashboard/components/UserVaults/hook.tsx
  src/features/data/actions/apy.ts
  src/features/data/actions/filtered-vaults.ts
  src/features/data/middlewares/apy.ts
  src/features/data/middlewares/filtered-vaults.ts
  src/features/data/reducers/apy.ts
  src/features/data/reducers/filtered-vaults.ts
  src/features/data/reducers/index.tsx
  src/features/data/selectors/filtered-vaults.ts
  src/helpers/number.ts
  src/store.ts
Labels: ux-ok

#2052 Add mantle kyber swap aggregator + enable zap for lendle
  src/config/vault/mantle.json
  src/config/zap/swap-aggregators.json
  src/features/data/apis/kyber/kyber.ts
Labels: ux-ok
